### ISSUE TITLE
so is it used not used for predictor in isolation?

### ISSUE THREAD

**Issue by Sandy4321** [IBMPredictiveAnalytics/Select_Predictors#1]
so is it used not used for predictor in isolation?
A univariable method that considers each predictor in isolation is used, as opposed to the multivariable method of selecting predictors that is used…

**Comment by JKPeck** [comment]
You can get more information on this by looking up SELECTPRED in the Command Syntax Reference or the Algorithms documentation.  But it is correct that this is a univariate method useful for screening when the number of predictors is large.

**Comment by Sandy4321** [comment]
can you share links and maybe videos how to use this IBM package ?

**Comment by JKPeck** [comment]
There are no links or videos for this custom dialog that I know of.  You can just use the SELECTPRED syntax as described in the Command Syntax Reference accessed from the Help menu, or you can install and use the dialog box, Select_Predictors.cdf from here.

To install this, first run SHOW EXT from a syntax window.  Look at the locations listed in the EXTPATHS CDIALOGS section of the output.  If there isn't a subdirectory named spss.enhanced, create it in one of the listed locations.  Copy the cfe file there.  Restart Statistics, and the dialog box will appear under Analyze > Dimension Reduction.

Note that if your dependent variable is categorical, you can use the NAIVEBAYES procedure, which considers all the variables together.

**Comment by Sandy4321** [comment]
I never used this IBM
Can I install it?
On my windows PC?

**Comment by JKPeck** [comment]
This is a free extension (actually just a custom dialog box) for IBM SPSS Statistics, which must be installed first,
